<?php

include(__DIR__ . '/../vendor/autoload.php');

$connections = array(
    'ADOdb\\drivers\\Connections\\access',
    'ADOdb\\drivers\\Connections\\ado',
    'ADOdb\\drivers\\Connections\\ado5',
    'ADOdb\\drivers\\Connections\\ado_access',
    'ADOdb\\drivers\\Connections\\ado_mssql',
    'ADOdb\\drivers\\Connections\\ads',
    'ADOdb\\drivers\\Connections\\borland_ibase',
    'ADOdb\\drivers\\Connections\\csv',
    'ADOdb\\drivers\\Connections\\db2',
    'ADOdb\\drivers\\Connections\\db2oci',
    'ADOdb\\drivers\\Connections\\fbsql',
    'ADOdb\\drivers\\Connections\\firebird',
    'ADOdb\\drivers\\Connections\\ibase',
    'ADOdb\\drivers\\Connections\\informix',
    'ADOdb\\drivers\\Connections\\informix72',
    'ADOdb\\drivers\\Connections\\ldap',
    'ADOdb\\drivers\\Connections\\mssql',
    // causes die() if extension unavailable
    //'ADOdb\\drivers\\Connections\\mssql_native',
    'ADOdb\\drivers\\Connections\\mssql_n',
    'ADOdb\\drivers\\Connections\\mssqlpo',
    'ADOdb\\drivers\\Connections\\mysql',
    'ADOdb\\drivers\\Connections\\mysqli',
    'ADOdb\\drivers\\Connections\\mysqlt',
    'ADOdb\\drivers\\Connections\\netezza',
    'ADOdb\\drivers\\Connections\\oci8',
    'ADOdb\\drivers\\Connections\\oci805',
    'ADOdb\\drivers\\Connections\\oci8po',
    'ADOdb\\drivers\\Connections\\oci8quercus',
    'ADOdb\\drivers\\Connections\\odbc',
    'ADOdb\\drivers\\Connections\\odbc_db2',
    'ADOdb\\drivers\\Connections\\odbc_mssql',
    'ADOdb\\drivers\\Connections\\odbc_mssql2012',
    'ADOdb\\drivers\\Connections\\odbc_oracle',
    'ADOdb\\drivers\\Connections\\odbtp',
    'ADOdb\\drivers\\Connections\\odbtp_unicode',
    'ADOdb\\drivers\\Connections\\oracle',
    'ADOdb\\drivers\\Connections\\pdo',
    'ADOdb\\drivers\\Connections\\pdo_base',
    'ADOdb\\drivers\\Connections\\pdo_mssql',
    'ADOdb\\drivers\\Connections\\pdo_mysql',
    'ADOdb\\drivers\\Connections\\pdo_oci',
    'ADOdb\\drivers\\Connections\\pdo_pgsql',
    'ADOdb\\drivers\\Connections\\pdo_sqlite',
    'ADOdb\\drivers\\Connections\\pdo_sqlsrv',
    'ADOdb\\drivers\\Connections\\postgres64',
    'ADOdb\\drivers\\Connections\\postgres7',
    'ADOdb\\drivers\\Connections\\postgres8',
    'ADOdb\\drivers\\Connections\\postgres9',
    'ADOdb\\drivers\\Connections\\proxy',
    'ADOdb\\drivers\\Connections\\sapdb',
    'ADOdb\\drivers\\Connections\\sqlanywhere',
    'ADOdb\\drivers\\Connections\\sqlite3',
    'ADOdb\\drivers\\Connections\\sqlite',
    'ADOdb\\drivers\\Connections\\sqlitepo',
    'ADOdb\\drivers\\Connections\\sybase',
    'ADOdb\\drivers\\Connections\\sybase_ase',
    'ADOdb\\drivers\\Connections\\text',
);

$record_sets = array(
    'ADOdb\\drivers\\RecordSets\\access',
    'ADOdb\\drivers\\RecordSets\\ado',
    'ADOdb\\drivers\\RecordSets\\ado5',
    'ADOdb\\drivers\\RecordSets\\ado_access',
    'ADOdb\\drivers\\RecordSets\\ado_mssql',
    'ADOdb\\drivers\\RecordSets\\ads',
    'ADOdb\\drivers\\RecordSets\\borland_ibase',
    'ADOdb\\drivers\\RecordSets\\csv',
    'ADOdb\\drivers\\RecordSets\\db2',
    'ADOdb\\drivers\\RecordSets\\db2oci',
    'ADOdb\\drivers\\RecordSets\\fbsql',
    'ADOdb\\drivers\\RecordSets\\firebird',
    'ADOdb\\drivers\\RecordSets\\ibase',
    'ADOdb\\drivers\\RecordSets\\informix',
    'ADOdb\\drivers\\RecordSets\\informix72',
    'ADOdb\\drivers\\RecordSets\\ldap',
    'ADOdb\\drivers\\RecordSets\\mssql',
    'ADOdb\\drivers\\RecordSets\\mssql_native',
    'ADOdb\\drivers\\RecordSets\\mssql_n',
    'ADOdb\\drivers\\RecordSets\\mssqlpo',
    'ADOdb\\drivers\\RecordSets\\mysql',
    'ADOdb\\drivers\\RecordSets\\mysqli',
    'ADOdb\\drivers\\RecordSets\\mysqlt',
    'ADOdb\\drivers\\RecordSets\\netezza',
    'ADOdb\\drivers\\RecordSets\\oci8',
    'ADOdb\\drivers\\RecordSets\\oci805',
    'ADOdb\\drivers\\RecordSets\\oci8po',
    'ADOdb\\drivers\\RecordSets\\oci8quercus',
    'ADOdb\\drivers\\RecordSets\\odbc',
    'ADOdb\\drivers\\RecordSets\\odbc_db2',
    'ADOdb\\drivers\\RecordSets\\odbc_mssql',
    'ADOdb\\drivers\\RecordSets\\odbc_mssql2012',
    'ADOdb\\drivers\\RecordSets\\odbc_oracle',
    'ADOdb\\drivers\\RecordSets\\odbtp',
    'ADOdb\\drivers\\RecordSets\\oracle',
    'ADOdb\\drivers\\RecordSets\\pdo',
    'ADOdb\\drivers\\RecordSets\\pdo_sqlsrv',
    'ADOdb\\drivers\\RecordSets\\postgres64',
    'ADOdb\\drivers\\RecordSets\\postgres7',
    'ADOdb\\drivers\\RecordSets\\postgres8',
    'ADOdb\\drivers\\RecordSets\\postgres9',
    'ADOdb\\drivers\\RecordSets\\proxy',
    'ADOdb\\drivers\\RecordSets\\sapdb',
    'ADOdb\\drivers\\RecordSets\\sqlanywhere',
    'ADOdb\\drivers\\RecordSets\\sqlite3',
    'ADOdb\\drivers\\RecordSets\\sqlite',
    'ADOdb\\drivers\\RecordSets\\sqlitepo',
    'ADOdb\\drivers\\RecordSets\\sybase',
    'ADOdb\\drivers\\RecordSets\\sybase_ase',
    'ADOdb\\drivers\\RecordSets\\text',
);

foreach ($connections as $con) {
    echo class_exists($con) ? "Found class {$con}" . PHP_EOL : "Missing class {$con}" . PHP_EOL;
}

foreach ($record_sets as $rs) {
    echo class_exists($rs) ? "Found class {$rs}" . PHP_EOL : "Missing class {$rs}" . PHP_EOL;
}
